server:
  port: 9585
  servlet:
    context-path: /maple
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: maple
  datasource:
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
    url: jdbc:mysql://192.168.112.128:3308/maple?serverTimezone=GMT&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password:
    host: 192.168.112.128
    lettuce:
      pool:
        max-active: 8 # 连接池大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的大空闲连接
        min-idle: 1 # 连接池中的小空闲连接
        max-wait: 1000 # 连接池大阻塞等待时间（使用负值表示没有限制
    port: 6379
    timeout: 100
#
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**.xml
logging:
  file:
    path: ./logs
  level.org.apache.ibatis.logging.stdout.StdOutImpl: debug

